interface ChampionSkinSet {
  [key: string]: string[]
}
const skinThemeSets: ChampionSkinSet = {
  Academy: ['Ahri', 'Darius', 'Ekko', 'Vladimir', 'Fiora', 'Ryze'],
  Albion: ['Morgana', 'Ezreal', 'Ashe', 'Kayle'],
  'Anima Squad': ['Vayne', 'Miss Fortune', 'Riven', 'Jinx', 'Sylas', 'Jinx'],
  Anniversary: ['Annie', 'Fiddlesticks'],
  'Arcade: Battle Bosses': ['Blitzcrank', 'Brand', 'Malzahar', 'Qiyana', 'Yasuo', 'Ziggs', 'Veigar'],
  'Arcade: Heroes': ['Ahri', 'Caitlyn', 'Corki', 'Ezreal', 'Hecarim', "Kai'Sa", 'Miss Fortune', 'Riven', 'Sona', 'Caitlyn'],
  Arcana: ['Ahri', 'Camille', 'Hecarim', 'Lucian', 'Rakan', 'Ryze', 'Tahm Kench', 'Xayah', 'Xerath'],
  Arcane: ['Caitlyn', 'Jayce', 'Jinx', 'Vi', 'Ekko'],
  Arcanists: ["Kog'Maw", 'Shaco', 'Zoe', 'Ziggs', 'Zoe', 'Lux'],
  Arclight: ['Brand', 'Varus', 'Vayne', "Vel'Koz", 'Yorick'],
  Justicar: ['Aatrox', 'Syndra'],
  'Ashen Knights': ['Pyke'],
  Astronauts: ['Bard', 'Corki', 'Gnar', 'Maokai', 'Poppy', 'Rammus', 'Teemo', 'Veigar', 'Nautilus'],
  'Battle Academia': ['Caitlyn', 'Ezreal', 'Garen', 'Jayce', 'Katarina', 'Leona', 'Lux', 'Wukong', 'Yone', 'Yuumi', 'Graves', 'Leona', 'Lux'],
  'Battle Queens': ['Diana', 'Janna', 'Katarina', 'Qiyana', 'Rell', 'Diana'],
  Battlecast: ["Kog'Maw", 'Nasus', 'Urgot', "Vel'Koz", 'Xerath', 'Zac', 'Skarner', "Cho'Gath", 'Viktor', 'Caitlyn', 'Illaoi', 'Jayce', 'Singed', 'Yorick'],
  'Bees!': ["Kog'Maw", 'Singed', 'Teemo', 'Malzahar', 'Ziggs', 'Heimerdinger', 'Nunu & Willump', 'Orianna', 'Yuumi'],
  'Bilgewater: Burning Tides': ['Rumble', 'Katarina', 'Swain', 'Tristana', 'Gangplank', 'Miss Fortune', 'Quinn', 'Twisted Fate', 'Graves', 'Fiddlesticks', 'Malphite', 'Twitch', 'Ryze', 'Garen', 'Aatrox'],
  'Bilgewater: Curse of the Drowned': ['Diana', 'Vladimir'],
  Blackfrost: ['Alistar', 'Anivia', "Rek'Sai", 'Renekton', 'Sion', "Vel'Koz"],
  'Blood Moon': ['Aatrox', 'Akali', 'Diana', 'Elise', 'Evelynn', 'Jhin', 'Kalista', 'Katarina', 'Kennen', 'Master Yi', 'Pyke', 'Shen', 'Sivir', 'Talon', 'Thresh', 'Tryndamere', 'Twisted Fate', 'Yasuo', 'Zilean', 'Aatrox'],
  Bloodstone: ['Hecarim', 'Vladimir', 'Renekton', 'Lissandra', 'Taric'],
  'Cafe Cuties': ['Annie', 'Bard', 'Gwen', 'Sivir', 'Soraka', 'Vladimir'],
  'Cats Versus Dogs': ['Nasus', 'Corki', 'Fizz', 'Maokai', 'Yorick', 'Fizz', 'Rengar', "Kog'Maw"],
  'Battle of the God-Kings': ['Darius', 'Garen'],
  Dawnbringer: ['Karma', 'Morgana', 'Nidalee', 'Soraka', 'Vex', 'Yone', 'Kayn'],
  Nightbringer: ['Aphelios', 'Kayn', 'Lee Sin', 'Lillia', 'Soraka', 'Tryndamere', 'Vladimir', 'Kayn', 'Lee Sin'],
  'Order Versus Chaos': ['Riven', 'Yasuo'],
  Forsaken: ['Jayce', 'Olaf'],
  'Star Wars': ['Master Yi', 'Jayce'],
  "Collector's Edition": ['Alistar', 'Kayle', 'Ryze'],
  Commando: ['Galio', 'Garen', 'Jarvan IV', 'Lux', 'Xin Zhao', 'Tristana', 'Gangplank'],
  'Cops and Robbers': ['Volibear', 'Trundle', 'Caitlyn', 'Vi', 'Twitch', 'Evelynn'],
  Riot: ['Blitzcrank', 'Graves', 'Kayle', 'Tristana', 'Nasus', 'Singed'],
  'Secret Agent': ['Miss Fortune', 'Xin Zhao'],
  Cottontail: ['Fizz', 'Teemo'],
  'Crime City': ['Braum', 'Graves', 'Jinx', 'Miss Fortune', 'Twitch', 'Gragas', 'Lee Sin'],
  'Crime City Nightmare': ['Akali', 'Darius', 'Shaco', 'Twisted Fate', 'Zyra'],
  Debonair: ['Brand', 'Draven', 'Ezreal', 'Galio', 'Jayce', 'LeBlanc', 'Leona', 'Malzahar', 'Master Yi', 'Vi', 'Zed', 'Brand'],
  'Crimson Elite': ['Riven', 'Talon'],
  'Crystal Rose': ['Akshan', 'Janna', 'Swain', 'Zyra'],
  'Withered Rose': ['Elise', 'Syndra', 'Talon', 'Zeri'],
  'Culinary Masters': ['Pantheon', 'Leona', 'Galio', 'Olaf', 'Tahm Kench', 'Sivir', 'Akali', 'Morgana'],
  'Cyber Pop': ['Akshan', 'Zoe'],
  'Day Job': ['Jax', 'Udyr', 'Blitzcrank', 'Dr. Mundo', 'Tristana', 'Fizz', 'Janna', 'Zilean', 'Heimerdinger', 'Trundle', 'Sion', 'Alistar', 'LeBlanc', 'Draven', 'Gangplank'],
  'Definitely Not': ['Blitzcrank', 'Udyr', "Vel'Koz", 'Draven'],
  'Demacia Vice': ['Garen', 'Lucian'],
  Demonic: ['Vi', 'Galio', 'Tristana', 'Fizz', 'Teemo'],
  'Dragon World': ['Galio', 'Mordekaiser', 'Swain', 'Udyr', 'Zyra', 'Heimerdinger', 'Lulu', 'Tristana', 'Braum', 'Diana', 'Jarvan IV', 'Kayle', 'Olaf', 'Pantheon', 'Trundle', 'Twitch', 'Vayne', 'Xin Zhao'],
  Dragonmancers: ['Yasuo', 'Volibear', 'Brand', 'Ashe', "Kai'Sa", 'Sett', 'Volibear', 'Sett', 'Thresh', 'Aurelion Sol', 'Lee Sin', 'Karma', 'Yasuo'],
  Dreadknights: ['Garen', 'Nasus'],
  Dunkmaster: ['Darius', 'Ivern'],
  Coven: ['Ahri', 'Ashe', 'Camille', 'Cassiopeia', 'Evelynn', 'LeBlanc', 'Lissandra', 'Morgana', 'Zyra', 'Ivern', 'Malphite', 'Nocturne', 'Warwick', 'LeBlanc', 'Zyra'],
  'Death Blossom': ['Elise', "Kha'Zix"],
  Eclipse: ['Aatrox', 'Leona', 'Senna', 'Senna', 'Leona', 'Sejuani', 'Sivir', 'Kayle'],
  Elderwood: ['Soraka', 'Ahri', 'Azir', 'Bard', 'Gnar', 'Hecarim', 'LeBlanc', 'Ornn', 'Rakan', "Rek'Sai", 'Veigar', 'Xayah', 'Taric', 'Ivern', 'Malphite', 'Nocturne', 'Warwick'],
  Eternum: ['Cassiopeia', 'Nocturne', "Rek'Sai"],
  Cosmic: ['Lux', 'Master Yi', 'Hecarim', 'Rakan', 'Xin Zhao', 'Nami', 'Vladimir', 'Xayah', 'Lulu', 'Anivia', 'Varus', 'Nidalee', 'Illaoi', 'Ashe', 'Kassadin', 'Skarner'],
  'Dark Star': ['Jhin', 'Lissandra', 'Lux', "Cho'Gath", 'Jarvan IV', 'Karma', "Kha'Zix", 'Malphite', 'Mordekaiser', 'Orianna', 'Shaco', 'Thresh', 'Varus', 'Xerath', 'Malphite'],
  Fables: ['Diana', 'Morgana', 'Veigar', "Cho'Gath", 'Sona', 'Nami', 'Nunu & Willump', 'Cassiopeia', 'Leona'],
  'Forgotten Depths': ['Nautilus', 'Fizz', 'Syndra', 'Malphite', 'Kassadin', "Kog'Maw", 'Nami', 'Thresh'],
  Freljord: ['Ashe', 'Rammus', 'Sylas', 'Taliyah'],
  Galactic: ['Azir', 'Nasus', 'Renekton'],
  Glacial: ['Ezreal', 'Shen', 'Nocturne', 'Malphite', 'Olaf', 'Shyvana'],
  Goth: ['Amumu', 'Annie', 'Orianna'],
  'Guardian of the Sands': ['Janna', "Kha'Zix", 'Rammus', 'Rengar', 'Ryze', 'Skarner', 'Xerath', 'Fiddlesticks', 'Pyke', 'Ekko', 'Katarina'],
  'Death Sworn': ['Katarina', 'Viktor', 'Zed', 'Hecarim', 'Soraka', 'Twisted Fate', 'Wukong'],
  'Trick-or-Treat': ['Elise', 'Fiora', 'Janna', 'Miss Fortune', 'Morgana', 'Nami', 'Nidalee', 'Poppy', 'Syndra', 'Tristana', 'Yuumi', 'Kassadin', 'Kled', 'Annie', 'Maokai', 'Zyra', 'Nocturne', 'Hecarim', 'Katarina', 'Fizz', 'Teemo', 'Dr. Mundo', 'Vladimir', 'Miss Fortune', 'Morgana', 'Amumu', 'Fiddlesticks', 'LeBlanc', 'Ekko', 'Twisted Fate', 'Blitzcrank'],
  'Zombies VS Slayers': ['Brand', 'Nunu & Willump', 'Ryze', 'Jinx', 'Pantheon'],
  Headhunter: ['Akali', 'Caitlyn', 'Master Yi', 'Nidalee', 'Rengar'],
  Heartbreakers: ['Vi', 'Fiora', 'Ashe', 'Jinx', 'Lucian', 'Orianna', 'Quinn', 'Varus', 'Vayne', 'Yuumi', 'Annie', 'Rakan', 'Sona', 'Xayah'],
  'Heavy Metal': ['Blitzcrank', 'Viktor', 'Jayce', 'Pantheon', 'Rammus', 'Nunu & Willump'],
  Hextech: ['Alistar', 'Amumu', 'Anivia', 'Annie', 'Galio', 'Janna', 'Jarvan IV', 'Kassadin', "Kog'Maw", 'Malzahar', 'Nocturne', 'Poppy', 'Rammus', 'Renekton', 'Sejuani', 'Singed', 'Sion', 'Swain', 'Tristana', 'Ziggs'],
  'High Noon': ['Fiddlesticks', 'Miss Fortune', 'Cassiopeia', 'Ashe', 'Darius', 'Hecarim', 'Irelia', 'Jhin', 'Katarina', 'Leona', 'Lucian', 'Mordekaiser', 'Samira', 'Senna', 'Sion', 'Tahm Kench', 'Talon', 'Thresh', 'Twisted Fate', 'Twitch', 'Urgot', 'Varus', 'Viktor', 'Yasuo', 'Alistar', 'Talon', 'Skarner', 'Caitlyn', "Kog'Maw"],
  'High Society': ['Nasus', 'Vayne', "Cho'Gath", 'Gnar', 'Vladimir'],
  'Immortal Journey': ['Irelia', 'Talon', 'Master Yi', 'Lee Sin', 'Jax', 'Morgana', 'Riven', 'Janna', 'Fiora', 'Nami', 'Riven'],
  Infernal: ['Aurelion Sol', 'Maokai', 'Warwick', 'Ahri', 'Akali', 'Alistar', 'Amumu', 'Diana', 'Galio', 'Karthus', 'Kennen', 'Mordekaiser', 'Nasus', 'Shen', 'Varus', "Vel'Koz", 'Rammus', 'Malphite', 'Renekton', 'Xerath', 'Kindred', 'Wukong', 'Zyra'],
  Invaders: ['Heimerdinger', 'Corki'],
  Lancer: ['Blitzcrank', 'Blitzcrank', 'Wukong', 'Hecarim'],
  Pharaoh: ['Amumu', 'Nasus', 'Nidalee'],
  Luchador: ['Gnar', 'Dr. Mundo', 'Volibear', 'Braum'],
  'Lunar Beast': ['Alistar', 'Annie', 'Aphelios', 'Darius', 'Fiora', 'Jarvan IV', 'Viego', 'Fiora'],
  'Lunar Revel': ['Tahm Kench', 'Lee Sin', 'Sona', 'Wukong', 'Cassiopeia', 'Lux', 'Diana', 'Nasus', 'Warwick', 'Caitlyn', 'Morgana', 'Sylas', 'Wukong'],
  'Lunar Revel: Firecracker': ['Corki', 'Diana', 'Jinx', 'Sejuani', 'Sett', 'Teemo', 'Tristana', 'Vayne', 'Xin Zhao', "Kog'Maw", 'Annie', 'Vayne'],
  'Lunar Revel: Warring Kingdoms': ['Riven', 'Talon', 'Azir', 'Garen', 'Jarvan IV', 'Katarina', 'Nidalee', 'Tryndamere', 'Vi', 'Xin Zhao'],
  'Mecha Kingdoms': ['Draven', 'Garen', 'Jax', 'Leona', 'Sett', 'Garen'],
  'Mad Scientists': ['Singed', 'Ziggs'],
  Marauder: ['Alistar', 'Ashe', 'Kalista', 'Kled', 'Olaf', 'Warwick', 'Xin Zhao'],
  Warden: ['Gragas', 'Jax', 'Karma', 'Nautilus', 'Quinn', 'Sivir'],
  Kaiju: ['Urgot'],
  Mecha: ['Aatrox', 'Aurelion Sol', "Kha'Zix", 'Malphite', 'Rengar', 'Sion'],
  Medieval: ['Poppy', 'Tryndamere', 'Amumu', 'Twitch', 'Ashe', 'Kled', 'Lux', 'Veigar'],
  'K/DA': ['Ahri', 'Akali', 'Evelynn', "Kai'Sa", 'Ahri', 'Ahri', 'Akali', 'Evelynn', "Kai'Sa"],
  'K/DA ALL OUT': ['Ahri', 'Akali', 'Evelynn', "Kai'Sa", 'Seraphine', 'Seraphine', 'Seraphine', "Kai'Sa"],
  Pentakill: ['Karthus', 'Kayle', 'Mordekaiser', 'Olaf', 'Sona', 'Yorick'],
  'Pentakill III: The Lost Chapter': ['Viego', 'Karthus', 'Kayle', 'Mordekaiser', 'Olaf', 'Sona', 'Yorick'],
  'True Damage': ['Qiyana', 'Senna', 'Yasuo', 'Akali', 'Ekko', 'Qiyana', 'Senna', 'Yasuo'],
  Odyssey: ['Zed', 'Aatrox', 'Jinx', 'Karma', 'Kayn', "Kha'Zix", 'Malphite', 'Sivir', 'Sona', 'Twisted Fate', 'Yasuo', 'Ziggs'],
  'Omega Squad': ['Fizz', 'Teemo', 'Tristana', 'Twitch', 'Veigar'],
  'Omen of the Dark': ['Singed', 'Lissandra', 'Nocturne', 'Dr. Mundo', 'Warwick', 'Kayle', 'Fiddlesticks', 'Yorick'],
  'Order of the Lotus': ['Irelia', 'Karma'],
  Papercraft: ['Anivia', 'Nunu & Willump'],
  PAX: ['Sivir', 'Jax', 'Sivir', 'Twisted Fate'],
  Phoenixmancers: ['Xayah', 'Anivia', 'Seraphine', 'Xayah'],
  'Piltover Customs': ['Corki', 'Blitzcrank', 'Heimerdinger'],
  'Pool Party': ['Braum', 'Caitlyn', 'Draven', 'Fiora', 'Gangplank', 'Graves', 'Heimerdinger', 'Jarvan IV', 'Lee Sin', 'Leona', 'Lulu', 'Miss Fortune', 'Orianna', "Rek'Sai", 'Renekton', 'Sett', 'Syndra', 'Taliyah', 'Taric', 'Zac', 'Ziggs', 'Zoe', 'Dr. Mundo', 'Singed'],
  Porcelain: ['Amumu', 'Kindred', 'Lissandra', 'Lux', 'Ezreal', 'Lux'],
  'Prehistoric Hunters': ['Draven', 'Sejuani', 'Tryndamere', 'Shyvana', 'Anivia', "Cho'Gath", 'Renekton', 'Ryze'],
  Program: ['Blitzcrank', 'Camille', 'LeBlanc', 'Lissandra', 'Nami', 'Soraka'],
  PROJECT: ['Irelia', 'Sylas', 'Zed', 'Akali', 'Ashe', 'Ekko', 'Fiora', 'Irelia', 'Jhin', 'Jinx', 'Katarina', 'Leona', 'Lucian', 'Mordekaiser', 'Pyke', 'Renekton', 'Sejuani', 'Senna', 'Sylas', 'Varus', 'Vayne', 'Vi', 'Warwick', 'Yasuo', 'Zed', 'Master Yi'],
  'Arctic Ops': ['Gragas', 'Kennen', 'Varus', 'Caitlyn', 'Swain', 'Volibear'],
  'Black Rose Group': ['Kayle', 'Pyke', 'Samira', 'Viktor', 'Zed'],
  PsyOps: ['Ezreal', 'Ezreal', 'Master Yi', 'Shen', 'Sona', 'Vi'],
  Praetorian: ['Fiddlesticks', 'Graves'],
  Pulsefire: ['Lucian', 'Thresh', 'Caitlyn', 'Ekko', 'Ezreal', 'Fiora', 'Lucian', 'Pantheon', 'Riven', 'Shen', 'Thresh', 'Twisted Fate'],
  'Rift Hospital': ['Kennen', 'Akali', 'Shen'],
  'Rift Quest': ['Sion', 'Bard', 'Braum', 'Nunu & Willump', 'Gragas', 'Jayce', 'Karthus', 'Mordekaiser', 'Dr. Mundo', 'Garen', 'Ryze', 'Sejuani', 'Talon', 'Taric', 'Twitch', 'Varus', 'Veigar'],
  'Road Warrior': ['Brand', 'Rumble', 'Veigar', 'Heimerdinger', 'Warwick', 'Trundle', 'Miss Fortune', 'Pantheon'],
  Vandal: ['Brand', 'Gragas', 'Jax', 'Twitch', 'Vladimir'],
  'Shan Hai Scrolls': ["Cho'Gath", 'Jhin', 'Nautilus', 'Neeko'],
  Shockblade: ['Kassadin', 'Qiyana', 'Shen', 'Zed'],
  'Silver Age': ['Singed', 'Darius', 'Tryndamere', 'Brand', 'Warwick', 'Irelia', 'Quinn', 'Kennen', 'Teemo', 'Veigar', 'Dr. Mundo'],
  'Snow Day': ['Bard', 'Gnar', 'Graves', 'Malzahar', 'Singed', 'Syndra', 'Ziggs'],
  'Snowdown Showdown': ['Jinx', 'Veigar', 'Miss Fortune', 'Tristana', 'Maokai', 'Teemo', 'LeBlanc', 'Shaco', 'Zilean', 'Amumu', "Kog'Maw", 'Braum', 'Draven', 'Gragas', 'Sona', 'Katarina', 'Nidalee', 'Heimerdinger', 'Nunu & Willump'],
  'Winter Wonder': ['Fiddlesticks', 'Irelia', 'Annie', 'Dr. Mundo', 'Twitch', 'Sejuani', 'Poppy', 'Master Yi', 'Sivir', 'Karma', 'Lulu', 'Neeko', 'Orianna', 'Soraka'],
  'Soccer Cup': ['Akali', 'Blitzcrank', 'Maokai', 'Lee Sin', 'Katarina', 'Twisted Fate', 'Ezreal', 'Lucian', 'Gragas', 'Alistar', 'Rammus'],
  'Space Groove': ['Lulu', 'Blitzcrank', 'Gwen', 'Lulu', 'Lux', 'Nasus', 'Nunu & Willump', 'Rumble', 'Samira'],
  Akana: ['Cassiopeia', 'Lillia', 'Riven', 'Thresh', 'Vayne'],
  Kanmei: ['Teemo', 'Ahri', 'Kindred', 'Teemo', 'Yasuo', 'Yone'],
  'Star Guardian': ['Urgot'],
  'Star Guardian Season 1': ['Lulu', 'Lux', 'Janna', 'Jinx', 'Lulu', 'Lux', 'Poppy'],
  'Star Guardian Season 2': ['Ezreal', 'Miss Fortune', 'Soraka', 'Soraka', 'Ahri', 'Ezreal', 'Miss Fortune', 'Soraka', 'Syndra'],
  'Star Guardian Season 3': ['Neeko', 'Neeko', 'Rakan', 'Xayah', 'Zoe'],
  'Steel Legion': ['Garen', 'Lux'],
  Dreadnova: ['Darius', 'Gangplank'],
  'Steel Valkyries': ['Renata Glasc', 'Kayle', 'Morgana', "Kai'Sa", 'Miss Fortune'],
  Highstakes: ['Ezreal', 'Twisted Fate', 'Mordekaiser', 'Syndra', 'Shaco'],
  Storybook: ['Annie', 'Warwick', "Kog'Maw", 'Vladimir', 'Shaco', 'Annie'],
  'Sugar Rush': ['Lulu', 'Ivern', 'Fiddlesticks', 'Poppy', 'Braum', 'Evelynn', 'Ziggs', 'Zilean'],
  'Super Galaxy': ['Annie', 'Elise', 'Fizz', 'Gnar', 'Kindred', 'Nidalee', 'Rumble', 'Shyvana'],
  Tango: ['Evelynn', 'Twisted Fate'],
  Ruined: ['Gangplank', 'Pantheon', 'Draven', 'Karma', 'Miss Fortune', 'Pantheon', 'Shyvana', 'Yasuo', 'Thresh'],
  'Sentinels of Light': ['Diana', 'Graves', 'Irelia', 'Olaf', 'Pyke', 'Rengar', 'Riven', 'Vayne'],
  'Thunder Lord': ['Ornn', 'Volibear'],
  'Toy Box': ['Gnar', 'Nunu & Willump', 'Alistar', "Kog'Maw", 'Poppy', 'Renekton', 'Orianna', 'Kennen', 'Gangplank'],
  Traditional: ['Karma', 'Lee Sin', 'Sejuani', 'Trundle'],
  'Winter Sports': ['Veigar', 'Kassadin', 'Corki', 'Anivia', 'Jax', 'Fiddlesticks', 'Amumu', 'Twitch'],
  Woad: ['Kayle', 'Morgana', 'Ashe', 'Darius', 'Quinn'],
  'Wonders of the World': ['Sejuani', 'Ahri', 'Anivia', 'Shaco', 'Lee Sin', 'Pantheon', 'Gragas', 'Renekton', 'Teemo', 'Malphite', 'Karthus', 'Gangplank', 'Tryndamere', 'Ryze', 'Tryndamere', 'Xin Zhao'],
  Challenger: ['Ahri', 'Nidalee'],
  Conqueror: ['Alistar', 'Jax', 'Karma', 'Nautilus', 'Varus', 'Jax'],
  Victorious: ['Aatrox', 'Blitzcrank', 'Elise', 'Graves', 'Janna', 'Jarvan IV', 'Lucian', 'Maokai', 'Morgana', 'Orianna', 'Sivir'],
  'World Champions: 2011': ['Corki', 'Gragas', 'Janna', 'Jarvan IV', 'Karthus'],
  'World Champions: 2012': ['Ezreal', 'Nunu & Willump', 'Orianna', 'Shen', 'Dr. Mundo'],
  'World Champions: 2013': ['Jax', 'Lee Sin', 'Vayne', 'Zed', 'Zyra'],
  'World Champions: 2014': ['Rengar', 'Singed', 'Talon', 'Thresh', 'Twitch'],
  'World Champions: 2015': ['Alistar', 'Azir', 'Elise', 'Kalista', 'Renekton', 'Ryze'],
  'World Champions: 2016': ['Ekko', 'Jhin', 'Nami', 'Olaf', 'Syndra', 'Zac'],
  'World Champions: 2017': ['Ezreal', 'Gnar', 'Jarvan IV', 'Rakan', 'Taliyah', 'Xayah'],
  'World Champions: 2018': ['Camille', 'Fiora', 'Irelia', "Kai'Sa", 'LeBlanc', 'Rakan'],
  'World Champions: 2019': ['Gangplank', 'Lee Sin', 'Malphite', 'Thresh', 'Vayne'],
  'World Champions: 2020': ['Jhin', 'Kennen', 'Leona', 'Nidalee', 'Twisted Fate'],
  'World Championship': ['Ashe', 'Kalista', "Kha'Zix", 'LeBlanc', 'Riven', 'Ryze', 'Shyvana', 'Thresh', 'Zed', 'Riven', 'Jarvan IV'],
  Worldbreaker: ['Karma', 'Hecarim', 'Malzahar', 'Maokai', 'Nasus', 'Nautilus', 'Sion', 'Trundle'],
  American: ['Anivia', 'Karthus', 'Ryze'],
  Arabian: ['Malzahar', 'Akali'],
  Baron: ['Veigar', 'Corki'],
  Brazilian: ['Anivia', 'Nami', 'Gangplank'],
  Disguise: ['Galio', 'Udyr', 'Gnar', 'Veigar', 'Nunu & Willump', 'Maokai', 'Yorick', 'Alistar', 'Ezreal', 'Lulu', 'Lux', 'Miss Fortune', 'Soraka', 'Urgot', 'Tristana', 'Rengar', 'Annie', 'Tahm Kench', 'Warwick', 'Nami', 'Corki', 'Warwick'],
  'Double Name': ['Bard', 'Draven', 'Dr. Mundo'],
  'Gladiator Era': ['Draven', 'Jax', 'Xin Zhao'],
  'Hired Gun': ['Graves', 'Lucian'],
  Jurassic: ["Cho'Gath", "Kog'Maw"],
  Musketeer: ['Twisted Fate', 'Fiora'],
  Nightmare: ["Cho'Gath", 'Tryndamere'],
  Panda: ['Annie', 'Teemo'],
  Prestigious: ['LeBlanc', 'Twisted Fate'],
  Prom: ['Amumu', 'Annie'],
  Reaper: ['Karthus', 'Hecarim', 'Soraka'],
  Rune: ['Skarner', 'Xerath'],
  Soulhunter: ['Kayn', 'Vayne', 'Vladimir'],
  Spectral: ['Fiddlesticks', 'Gangplank'],
  'Surprise Party': ['Amumu', 'Fiddlesticks'],
  Void: ['Fizz', 'Nocturne', 'Illaoi'],
  Waterloo: ['Gangplank', 'Miss Fortune'],
  'Web Browser': ['Rammus', 'Ezreal', 'Ahri', 'Caitlyn'],
  Workshop: ['Nunu & Willump', 'Shaco'],
  'World Champions: 2021': ['Aphelios', 'Graves', 'Viego', 'Yuumi', 'Zoe'],
};

export default skinThemeSets;
